// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_Ticket_Booking_Backend.Data;

#nullable disable

namespace Movie_Ticket_Booking_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316060003_SeedGenres")]
    partial class SeedGenres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Blogs.BlogPost", b =>
                {
                    b.Property<string>("BlogPostId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BlogPostId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Blogs.Comment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BlogPostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CommentId");

                    b.HasIndex("BlogPostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShowtimeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.BookingFoodCombo", b =>
                {
                    b.Property<string>("BookingFoodComboId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FoodComboId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("BookingFoodComboId");

                    b.HasIndex("BookingId");

                    b.HasIndex("FoodComboId");

                    b.ToTable("BookingFoodCombos");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.BookingSeat", b =>
                {
                    b.Property<string>("BookingSeatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShowtimeTicketTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookingSeatId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ShowtimeTicketTypeId");

                    b.HasIndex("SeatId", "ShowtimeTicketTypeId")
                        .IsUnique();

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.BookingVoucher", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VoucherId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId", "VoucherId");

                    b.HasIndex("VoucherId");

                    b.ToTable("BookingVouchers");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Cinema", b =>
                {
                    b.Property<string>("CinemaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CinemaId");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CinemaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Seat", b =>
                {
                    b.Property<string>("SeatId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SeatName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowtimeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ShowtimeId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.SeatLock", b =>
                {
                    b.Property<string>("SeatLockId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShowtimeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SeatLockId");

                    b.HasIndex("SeatId");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("SeatLocks");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Foods.FoodCombo", b =>
                {
                    b.Property<string>("FoodComboId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodComboId");

                    b.ToTable("FoodCombos");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Cast", b =>
                {
                    b.Property<string>("CastId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CastId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            CastId = "CAST001",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/rdj.jpg",
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            CastId = "CAST002",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/cevans.jpg",
                            Name = "Chris Evans"
                        },
                        new
                        {
                            CastId = "CAST003",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/scarlett.jpg",
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            CastId = "CAST004",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/tomholland.jpg",
                            Name = "Tom Holland"
                        },
                        new
                        {
                            CastId = "CAST005",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/zendaya.jpg",
                            Name = "Zendaya"
                        },
                        new
                        {
                            CastId = "CAST006",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/pattinson.jpg",
                            Name = "Robert Pattinson"
                        },
                        new
                        {
                            CastId = "CAST007",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/zoe.jpg",
                            Name = "Zoë Kravitz"
                        },
                        new
                        {
                            CastId = "CAST008",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/cumberbatch.jpg",
                            Name = "Benedict Cumberbatch"
                        },
                        new
                        {
                            CastId = "CAST009",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/olsen.jpg",
                            Name = "Elizabeth Olsen"
                        },
                        new
                        {
                            CastId = "CAST010",
                            AvatarUrl = "https://image.tmdb.org/t/p/w500/reynolds.jpg",
                            Name = "Ryan Reynolds"
                        });
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Genre", b =>
                {
                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = "GEN001",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3609),
                            Name = "Action",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3613)
                        },
                        new
                        {
                            GenreId = "GEN002",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3614),
                            Name = "Adventure",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3615)
                        },
                        new
                        {
                            GenreId = "GEN003",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3616),
                            Name = "Animation",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3617)
                        },
                        new
                        {
                            GenreId = "GEN004",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3618),
                            Name = "Biography",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3619)
                        },
                        new
                        {
                            GenreId = "GEN005",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3620),
                            Name = "Comedy",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3621)
                        },
                        new
                        {
                            GenreId = "GEN006",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3622),
                            Name = "Crime",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3622)
                        },
                        new
                        {
                            GenreId = "GEN007",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3624),
                            Name = "Documentary",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3624)
                        },
                        new
                        {
                            GenreId = "GEN008",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3626),
                            Name = "Drama",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3626)
                        },
                        new
                        {
                            GenreId = "GEN009",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3627),
                            Name = "Family",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3628)
                        },
                        new
                        {
                            GenreId = "GEN010",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3629),
                            Name = "Fantasy",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3630)
                        },
                        new
                        {
                            GenreId = "GEN011",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3631),
                            Name = "History",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3631)
                        },
                        new
                        {
                            GenreId = "GEN012",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3633),
                            Name = "Horror",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3633)
                        },
                        new
                        {
                            GenreId = "GEN013",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3634),
                            Name = "Music",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3635)
                        },
                        new
                        {
                            GenreId = "GEN014",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3636),
                            Name = "Mystery",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3637)
                        },
                        new
                        {
                            GenreId = "GEN015",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3638),
                            Name = "Romance",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3639)
                        },
                        new
                        {
                            GenreId = "GEN016",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3640),
                            Name = "Sci-Fi",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3640)
                        },
                        new
                        {
                            GenreId = "GEN017",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3642),
                            Name = "Sport",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3642)
                        },
                        new
                        {
                            GenreId = "GEN018",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3643),
                            Name = "Thriller",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3644)
                        },
                        new
                        {
                            GenreId = "GEN019",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3645),
                            Name = "War",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3646)
                        },
                        new
                        {
                            GenreId = "GEN020",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3647),
                            Name = "Western",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3648)
                        },
                        new
                        {
                            GenreId = "GEN021",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3649),
                            Name = "Superhero",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3649)
                        },
                        new
                        {
                            GenreId = "GEN022",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3651),
                            Name = "Psychological",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3651)
                        },
                        new
                        {
                            GenreId = "GEN023",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3652),
                            Name = "Anime",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3653)
                        },
                        new
                        {
                            GenreId = "GEN024",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3654),
                            Name = "Disaster",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3655)
                        },
                        new
                        {
                            GenreId = "GEN025",
                            CreatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3656),
                            Name = "Martial Arts",
                            UpdatedAt = new DateTime(2026, 3, 16, 6, 0, 1, 779, DateTimeKind.Utc).AddTicks(3656)
                        });
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = "MOV001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Avengers assemble for the final battle against Thanos.",
                            Duration = 181.0,
                            Rating = 8.4000000000000004,
                            Status = "NOWSHOWING",
                            Title = "Avengers: Endgame",
                            TrailerUrl = "https://www.youtube.com/watch?v=TcMBFSGVi1c",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Spider-Man faces villains from different universes.",
                            Duration = 148.0,
                            Rating = 8.1999999999999993,
                            Status = "NOWSHOWING",
                            Title = "Spider-Man: No Way Home",
                            TrailerUrl = "https://www.youtube.com/watch?v=JfVOs4VSpmA",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV003",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Batman investigates corruption in Gotham.",
                            Duration = 176.0,
                            Rating = 7.9000000000000004,
                            Status = "NOWSHOWING",
                            Title = "The Batman",
                            TrailerUrl = "https://www.youtube.com/watch?v=mqqft2x_Aa4",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV004",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Doctor Strange explores the multiverse.",
                            Duration = 126.0,
                            Rating = 7.0,
                            Status = "NOWSHOWING",
                            Title = "Doctor Strange in the Multiverse of Madness",
                            TrailerUrl = "https://www.youtube.com/watch?v=aWzlQ2N6qqg",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV005",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deadpool meets Wolverine in a chaotic adventure.",
                            Duration = 130.0,
                            Rating = 0.0,
                            Status = "COMINGSOON",
                            Title = "Deadpool & Wolverine",
                            TrailerUrl = "https://www.youtube.com/watch?v=73_1biulkYk",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV006",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Arthur Fleck continues his descent into madness.",
                            Duration = 138.0,
                            Rating = 0.0,
                            Status = "COMINGSOON",
                            Title = "Joker: Folie à Deux",
                            TrailerUrl = "https://www.youtube.com/watch?v=xy8aJw1vYHo",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV007",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Po trains a new dragon warrior.",
                            Duration = 95.0,
                            Rating = 0.0,
                            Status = "COMINGSOON",
                            Title = "Kung Fu Panda 4",
                            TrailerUrl = "https://www.youtube.com/watch?v=_inKs4eeHiI",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV008",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ethan Hunt returns for his most dangerous mission.",
                            Duration = 160.0,
                            Rating = 0.0,
                            Status = "COMINGSOON",
                            Title = "Mission Impossible 8",
                            TrailerUrl = "https://www.youtube.com/watch?v=avz06PDqDbM",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV009",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jake Sully protects his family on Pandora.",
                            Duration = 192.0,
                            Rating = 7.7000000000000002,
                            Status = "NOWSHOWING",
                            Title = "Avatar: The Way of Water",
                            TrailerUrl = "https://www.youtube.com/watch?v=d9MyW72ELq0",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MovieId = "MOV010",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maverick trains a new generation of pilots.",
                            Duration = 131.0,
                            Rating = 8.3000000000000007,
                            Status = "NOWSHOWING",
                            Title = "Top Gun: Maverick",
                            TrailerUrl = "https://www.youtube.com/watch?v=giXco2jaZ_4",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.MovieCast", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CastId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CharacterAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId", "CastId");

                    b.HasIndex("CastId");

                    b.ToTable("MovieCasts");

                    b.HasData(
                        new
                        {
                            MovieId = "MOV001",
                            CastId = "CAST001",
                            CharacterAvatar = "",
                            CharacterName = "Iron Man"
                        },
                        new
                        {
                            MovieId = "MOV001",
                            CastId = "CAST002",
                            CharacterAvatar = "",
                            CharacterName = "Captain America"
                        },
                        new
                        {
                            MovieId = "MOV001",
                            CastId = "CAST003",
                            CharacterAvatar = "",
                            CharacterName = "Black Widow"
                        },
                        new
                        {
                            MovieId = "MOV002",
                            CastId = "CAST004",
                            CharacterAvatar = "",
                            CharacterName = "Spider-Man"
                        },
                        new
                        {
                            MovieId = "MOV002",
                            CastId = "CAST005",
                            CharacterAvatar = "",
                            CharacterName = "MJ"
                        },
                        new
                        {
                            MovieId = "MOV003",
                            CastId = "CAST006",
                            CharacterAvatar = "",
                            CharacterName = "Batman"
                        },
                        new
                        {
                            MovieId = "MOV003",
                            CastId = "CAST007",
                            CharacterAvatar = "",
                            CharacterName = "Catwoman"
                        },
                        new
                        {
                            MovieId = "MOV004",
                            CastId = "CAST008",
                            CharacterAvatar = "",
                            CharacterName = "Doctor Strange"
                        },
                        new
                        {
                            MovieId = "MOV004",
                            CastId = "CAST009",
                            CharacterAvatar = "",
                            CharacterName = "Scarlet Witch"
                        },
                        new
                        {
                            MovieId = "MOV005",
                            CastId = "CAST010",
                            CharacterAvatar = "",
                            CharacterName = "Deadpool"
                        });
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.MovieGenre", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.MovieRating", b =>
                {
                    b.Property<string>("MovieRatingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("MovieRatingId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("MovieRatings");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Poster", b =>
                {
                    b.Property<string>("PosterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PosterId");

                    b.HasIndex("MovieId");

                    b.ToTable("Posters");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.WatchList", b =>
                {
                    b.Property<string>("WatchListId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WatchListId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Payments.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Payments.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", b =>
                {
                    b.Property<string>("ShowtimeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowtimeId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Showtimes");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.ShowtimeTicketType", b =>
                {
                    b.Property<string>("ShowtimeTicketTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ShowtimeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TicketTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ShowtimeTicketTypeId");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("ShowtimeTicketTypes");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.TicketType", b =>
                {
                    b.Property<string>("TicketTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketTypeId");

                    b.ToTable("TicketTypes");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Users.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Users.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Vouchers.Voucher", b =>
                {
                    b.Property<string>("VoucherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("VoucherId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Blogs.BlogPost", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.User", "User")
                        .WithMany("BlogPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Blogs.Comment", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Blogs.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.BookingFoodCombo", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", "Booking")
                        .WithMany("BookingFoodCombos")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Foods.FoodCombo", "FoodCombo")
                        .WithMany("BookingFoodCombos")
                        .HasForeignKey("FoodComboId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("FoodCombo");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.BookingSeat", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Cinemas.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Showtimes.ShowtimeTicketType", "ShowtimeTicketType")
                        .WithMany("BookingSeats")
                        .HasForeignKey("ShowtimeTicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");

                    b.Navigation("ShowtimeTicketType");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.BookingVoucher", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", "Booking")
                        .WithMany("BookingVouchers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Vouchers.Voucher", "Voucher")
                        .WithMany("BookingVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Room", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Cinemas.Cinema", "Cinema")
                        .WithMany("Rooms")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Seat", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Cinemas.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", "Showtime")
                        .WithMany()
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Showtime");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.SeatLock", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Cinemas.Seat", "Seat")
                        .WithMany("SeatLocks")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", "Showtime")
                        .WithMany("SeatLocks")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.User", "User")
                        .WithMany("SeatLocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.MovieCast", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Cast", "Cast")
                        .WithMany("MovieCasts")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", "Movie")
                        .WithMany("MovieCasts")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.MovieGenre", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.MovieRating", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.User", "User")
                        .WithMany("MovieRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Poster", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", "Movie")
                        .WithMany("Posters")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.WatchList", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", "Movie")
                        .WithMany("WatchLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.User", "User")
                        .WithMany("WatchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Payments.Payment", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("Movie_Ticket_Booking_Backend.Domain.Payments.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Payments.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Cinemas.Room", "Room")
                        .WithMany("Showtimes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.ShowtimeTicketType", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", "Showtime")
                        .WithMany("ShowtimeTicketTypes")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Showtimes.TicketType", "TicketType")
                        .WithMany("ShowtimeTicketTypes")
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Users.User", b =>
                {
                    b.HasOne("Movie_Ticket_Booking_Backend.Domain.Users.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Blogs.BlogPost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("BookingFoodCombos");

                    b.Navigation("BookingSeats");

                    b.Navigation("BookingVouchers");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Cinema", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Cinemas.Seat", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("SeatLocks");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Foods.FoodCombo", b =>
                {
                    b.Navigation("BookingFoodCombos");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Cast", b =>
                {
                    b.Navigation("MovieCasts");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Movies.Movie", b =>
                {
                    b.Navigation("MovieCasts");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieRatings");

                    b.Navigation("Posters");

                    b.Navigation("Showtimes");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Payments.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.Showtime", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("SeatLocks");

                    b.Navigation("ShowtimeTicketTypes");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.ShowtimeTicketType", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Showtimes.TicketType", b =>
                {
                    b.Navigation("ShowtimeTicketTypes");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Users.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Users.User", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Bookings");

                    b.Navigation("Comments");

                    b.Navigation("MovieRatings");

                    b.Navigation("SeatLocks");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("Movie_Ticket_Booking_Backend.Domain.Vouchers.Voucher", b =>
                {
                    b.Navigation("BookingVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
